### ISSUE TITLE
Clarify "add element" buttons

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-VraCore#41]
For many of the elements, there is a green "Add [whatever] element" button - such as "Add Subject element" or "Add Textref Element". However, these don't add an input of the top level element (as in the case in Dublin core) but rather add a Subject/Textref/whatever subelement. Maybe we could change the language on the buttons to make that clearer?

And is the limitation of one subject/textref/etc part of VRA core?

**Comment by patrickmj** [comment]
It gets tricky because of Omeka and VRA using the same term for different things, and the difficulty of forcing XML ideas into Omeka. In VRA-land, I'm pretty sure that those are called elements, as in XML elements. Then, those have their own subelements. So we'd get to a name collision there, too. I'll think about other alternatives, but nothing springs to mind now. I think most people don't know how Omeka uses the word 'element', so I'm not sure how widespread the confusion would be.

The second question gets deeper into the problems of squishing VRA Core data into Omeka. There can be many subject/textref/etc VRA elements, but only one display value. That's why the usual Omeka input is treated as the display value, and I've removed the usual "Add Input" button there.
