### ISSUE TITLE
Should date elements have type attributes?

### ISSUE THREAD

**Issue by kimisgold** [omeka/plugin-VraCore#96]
I'm trying to create this block of XML from <a href="http://core.vraweb.org/examples/html/example001_full_xml.html">this example from the VRA website</a>:

```
<dateSet>
    <display>begun 1194 (creation); consecrated 1260 (other)</display>
    <notes>Louis IX (Saint Louis) present for consecration in 1260.</notes>
    <date type="creation">
        <earliestDate>1194</earliestDate>
        <latestDate>1194</latestDate>
    </date>
    <date type="other">
        <earliestDate>1260</earliestDate>
        <latestDate>1260</latestDate>
    </date>
</dateSet>
```

Where would I enter the 'type' attribute?

**Comment by patrickmj** [comment]
Looks like at some point I lost the part of the form for that, so it's a new bug

**Comment by patrickmj** [comment]
While essentially fixed, it leaves the possible case that when someone tries to enter only attributes on the Date (no subelement data), the attribute isn't saved. It's a little wonky, but seems a rare case, since people should always be entering that subelement data. Changing that would lead into the realm of validating data entry, which might be too big of a task given the rules in the schema.

**Comment by patrickmj** [comment]
Ready for @kimisgold to take a look at.
